version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    volumes:
      - ./backend/public:/app/public
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
    depends_on:
      - postgres
    networks:
      - full-auth-network
    entrypoint: ["sh", "/app/scripts/entrypoint.sh"]

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    networks:
      - full-auth-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user_postgres
      POSTGRES_PASSWORD: pass_postgres
    ports:
      - "5432:5432"
    volumes:
      - full-auth-data:/var/lib/postgresql/data
    networks:
      - full-auth-network

networks:
  full-auth-network:
    driver: bridge

volumes:
  full-auth-data:
    driver: local
